// Autogenerated by internal/cmd/embed. DO NOT EDIT.

package postgres

import (
	_ "embed"
	"unique"
)

var (
	//go:embed query/init/SelectVersion.sql
	initSelectVersion string
	//go:embed query/init/SelectWorkMem.sql
	initSelectWorkMem string
	//go:embed query/matcher/BeginUpdaterRun.sql
	matcherBeginUpdaterRun string
	//go:embed query/matcher/CompleteRun.sql
	matcherCompleteRun string
	//go:embed query/matcher/CreateRun.sql
	matcherCreateRun string
	//go:embed query/matcher/CreateUpdaterRun.sql
	matcherCreateUpdaterRun string
	//go:embed query/matcher/GetAdvisories.sql
	matcherGetAdvisories string
	//go:embed query/matcher/GetUpdateOperations.sql
	matcherGetUpdateOperations string
	//go:embed query/matcher/GetUpdaterID.sql
	matcherGetUpdaterID string
	//go:embed query/matcher/Initialized.sql
	matcherInitialized string
	//go:embed query/matcher/MarkUpdaterError.sql
	matcherMarkUpdaterError string
)

// NameLookup maps interned SQL text back to a developer-meaningful name if the
// query is an embedded string.
var NameLookup = map[unique.Handle[string]]string{
	unique.Make(initSelectVersion):          "SelectVersion",
	unique.Make(initSelectWorkMem):          "SelectWorkMem",
	unique.Make(matcherBeginUpdaterRun):     "BeginUpdaterRun",
	unique.Make(matcherCompleteRun):         "CompleteRun",
	unique.Make(matcherCreateRun):           "CreateRun",
	unique.Make(matcherCreateUpdaterRun):    "CreateUpdaterRun",
	unique.Make(matcherGetAdvisories):       "GetAdvisories",
	unique.Make(matcherGetUpdateOperations): "GetUpdateOperations",
	unique.Make(matcherGetUpdaterID):        "GetUpdaterID",
	unique.Make(matcherInitialized):         "Initialized",
	unique.Make(matcherMarkUpdaterError):    "MarkUpdaterError",
}

// TableLookup maps interned SQL text back to the "main" table affected by the
// query.
var TableLookup = map[unique.Handle[string]]string{
	unique.Make(initSelectVersion):      "libvuln_migrations",
	unique.Make(initSelectWorkMem):      "pg_settings",
	unique.Make(matcherBeginUpdaterRun): "updater_v1.run",
	// matcherCompleteRun: no obvious table
	// matcherCreateRun: no obvious table
	// matcherCreateUpdaterRun: no obvious table
	unique.Make(matcherGetAdvisories):       "updater_v1.run",
	unique.Make(matcherGetUpdateOperations): "matcher_v2.run",
	// matcherGetUpdaterID: no obvious table
	unique.Make(matcherInitialized):      "matcher_v2.run",
	unique.Make(matcherMarkUpdaterError): "matcher_v2.updater_run",
}

// OpLookup maps interned SQL text back to the kind of operation it is.
var OpLookup = map[unique.Handle[string]]string{
	unique.Make(initSelectVersion):          "SELECT",
	unique.Make(initSelectWorkMem):          "SELECT",
	unique.Make(matcherBeginUpdaterRun):     "INSERT",
	unique.Make(matcherCompleteRun):         "SELECT",
	unique.Make(matcherCreateRun):           "SELECT",
	unique.Make(matcherCreateUpdaterRun):    "SELECT",
	unique.Make(matcherGetAdvisories):       "SELECT",
	unique.Make(matcherGetUpdateOperations): "SELECT",
	unique.Make(matcherGetUpdaterID):        "SELECT",
	unique.Make(matcherInitialized):         "SELECT",
	unique.Make(matcherMarkUpdaterError):    "UPDATE",
}
