// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/quay/claircore/updater/driver (interfaces: AdvisoryBuilder)
//
// Generated by this command:
//
//	mockgen -package=drivertest -typed=true -write_package_comment=false -destination=advisory_builder_mock.go -mock_names AdvisoryBuilder=AdvisoryBuilder github.com/quay/claircore/updater/driver AdvisoryBuilder
//

package drivertest

import (
	context "context"
	iter "iter"
	reflect "reflect"
	time "time"

	driver "github.com/quay/claircore/updater/driver"
	gomock "go.uber.org/mock/gomock"
)

// AdvisoryBuilder is a mock of AdvisoryBuilder interface.
type AdvisoryBuilder struct {
	ctrl     *gomock.Controller
	recorder *AdvisoryBuilderMockRecorder
	isgomock struct{}
}

// AdvisoryBuilderMockRecorder is the mock recorder for AdvisoryBuilder.
type AdvisoryBuilderMockRecorder struct {
	mock *AdvisoryBuilder
}

// NewAdvisoryBuilder creates a new mock instance.
func NewAdvisoryBuilder(ctrl *gomock.Controller) *AdvisoryBuilder {
	mock := &AdvisoryBuilder{ctrl: ctrl}
	mock.recorder = &AdvisoryBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *AdvisoryBuilder) EXPECT() *AdvisoryBuilderMockRecorder {
	return m.recorder
}

// Abandon mocks base method.
func (m *AdvisoryBuilder) Abandon(ctx context.Context, reason error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Abandon", ctx, reason)
}

// Abandon indicates an expected call of Abandon.
func (mr *AdvisoryBuilderMockRecorder) Abandon(ctx, reason any) *AdvisoryBuilderAbandonCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Abandon", reflect.TypeOf((*AdvisoryBuilder)(nil).Abandon), ctx, reason)
	return &AdvisoryBuilderAbandonCall{Call: call}
}

// AdvisoryBuilderAbandonCall wrap *gomock.Call
type AdvisoryBuilderAbandonCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *AdvisoryBuilderAbandonCall) Return() *AdvisoryBuilderAbandonCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *AdvisoryBuilderAbandonCall) Do(f func(context.Context, error)) *AdvisoryBuilderAbandonCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *AdvisoryBuilderAbandonCall) DoAndReturn(f func(context.Context, error)) *AdvisoryBuilderAbandonCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AddArtifact mocks base method.
func (m *AdvisoryBuilder) AddArtifact(arg0 context.Context, arg1 driver.ArtifactHandle) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddArtifact", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddArtifact indicates an expected call of AddArtifact.
func (mr *AdvisoryBuilderMockRecorder) AddArtifact(arg0, arg1 any) *AdvisoryBuilderAddArtifactCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddArtifact", reflect.TypeOf((*AdvisoryBuilder)(nil).AddArtifact), arg0, arg1)
	return &AdvisoryBuilderAddArtifactCall{Call: call}
}

// AdvisoryBuilderAddArtifactCall wrap *gomock.Call
type AdvisoryBuilderAddArtifactCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *AdvisoryBuilderAddArtifactCall) Return(arg0 error) *AdvisoryBuilderAddArtifactCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *AdvisoryBuilderAddArtifactCall) Do(f func(context.Context, driver.ArtifactHandle) error) *AdvisoryBuilderAddArtifactCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *AdvisoryBuilderAddArtifactCall) DoAndReturn(f func(context.Context, driver.ArtifactHandle) error) *AdvisoryBuilderAddArtifactCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Aliases mocks base method.
func (m *AdvisoryBuilder) Aliases(arg0 context.Context, arg1 []driver.Alias) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Aliases", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Aliases indicates an expected call of Aliases.
func (mr *AdvisoryBuilderMockRecorder) Aliases(arg0, arg1 any) *AdvisoryBuilderAliasesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Aliases", reflect.TypeOf((*AdvisoryBuilder)(nil).Aliases), arg0, arg1)
	return &AdvisoryBuilderAliasesCall{Call: call}
}

// AdvisoryBuilderAliasesCall wrap *gomock.Call
type AdvisoryBuilderAliasesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *AdvisoryBuilderAliasesCall) Return(arg0 error) *AdvisoryBuilderAliasesCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *AdvisoryBuilderAliasesCall) Do(f func(context.Context, []driver.Alias) error) *AdvisoryBuilderAliasesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *AdvisoryBuilderAliasesCall) DoAndReturn(f func(context.Context, []driver.Alias) error) *AdvisoryBuilderAliasesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Attrs mocks base method.
func (m *AdvisoryBuilder) Attrs(arg0 context.Context, arg1 iter.Seq2[string, string]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Attrs", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Attrs indicates an expected call of Attrs.
func (mr *AdvisoryBuilderMockRecorder) Attrs(arg0, arg1 any) *AdvisoryBuilderAttrsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Attrs", reflect.TypeOf((*AdvisoryBuilder)(nil).Attrs), arg0, arg1)
	return &AdvisoryBuilderAttrsCall{Call: call}
}

// AdvisoryBuilderAttrsCall wrap *gomock.Call
type AdvisoryBuilderAttrsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *AdvisoryBuilderAttrsCall) Return(arg0 error) *AdvisoryBuilderAttrsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *AdvisoryBuilderAttrsCall) Do(f func(context.Context, iter.Seq2[string, string]) error) *AdvisoryBuilderAttrsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *AdvisoryBuilderAttrsCall) DoAndReturn(f func(context.Context, iter.Seq2[string, string]) error) *AdvisoryBuilderAttrsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Build mocks base method.
func (m *AdvisoryBuilder) Build(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Build", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Build indicates an expected call of Build.
func (mr *AdvisoryBuilderMockRecorder) Build(arg0 any) *AdvisoryBuilderBuildCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Build", reflect.TypeOf((*AdvisoryBuilder)(nil).Build), arg0)
	return &AdvisoryBuilderBuildCall{Call: call}
}

// AdvisoryBuilderBuildCall wrap *gomock.Call
type AdvisoryBuilderBuildCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *AdvisoryBuilderBuildCall) Return(arg0 error) *AdvisoryBuilderBuildCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *AdvisoryBuilderBuildCall) Do(f func(context.Context) error) *AdvisoryBuilderBuildCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *AdvisoryBuilderBuildCall) DoAndReturn(f func(context.Context) error) *AdvisoryBuilderBuildCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Description mocks base method.
func (m *AdvisoryBuilder) Description(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Description", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Description indicates an expected call of Description.
func (mr *AdvisoryBuilderMockRecorder) Description(arg0, arg1 any) *AdvisoryBuilderDescriptionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Description", reflect.TypeOf((*AdvisoryBuilder)(nil).Description), arg0, arg1)
	return &AdvisoryBuilderDescriptionCall{Call: call}
}

// AdvisoryBuilderDescriptionCall wrap *gomock.Call
type AdvisoryBuilderDescriptionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *AdvisoryBuilderDescriptionCall) Return(arg0 error) *AdvisoryBuilderDescriptionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *AdvisoryBuilderDescriptionCall) Do(f func(context.Context, string) error) *AdvisoryBuilderDescriptionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *AdvisoryBuilderDescriptionCall) DoAndReturn(f func(context.Context, string) error) *AdvisoryBuilderDescriptionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Issued mocks base method.
func (m *AdvisoryBuilder) Issued(arg0 context.Context, arg1 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Issued", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Issued indicates an expected call of Issued.
func (mr *AdvisoryBuilderMockRecorder) Issued(arg0, arg1 any) *AdvisoryBuilderIssuedCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Issued", reflect.TypeOf((*AdvisoryBuilder)(nil).Issued), arg0, arg1)
	return &AdvisoryBuilderIssuedCall{Call: call}
}

// AdvisoryBuilderIssuedCall wrap *gomock.Call
type AdvisoryBuilderIssuedCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *AdvisoryBuilderIssuedCall) Return(arg0 error) *AdvisoryBuilderIssuedCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *AdvisoryBuilderIssuedCall) Do(f func(context.Context, time.Time) error) *AdvisoryBuilderIssuedCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *AdvisoryBuilderIssuedCall) DoAndReturn(f func(context.Context, time.Time) error) *AdvisoryBuilderIssuedCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Links mocks base method.
func (m *AdvisoryBuilder) Links(arg0 context.Context, arg1 []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Links", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Links indicates an expected call of Links.
func (mr *AdvisoryBuilderMockRecorder) Links(arg0, arg1 any) *AdvisoryBuilderLinksCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Links", reflect.TypeOf((*AdvisoryBuilder)(nil).Links), arg0, arg1)
	return &AdvisoryBuilderLinksCall{Call: call}
}

// AdvisoryBuilderLinksCall wrap *gomock.Call
type AdvisoryBuilderLinksCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *AdvisoryBuilderLinksCall) Return(arg0 error) *AdvisoryBuilderLinksCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *AdvisoryBuilderLinksCall) Do(f func(context.Context, []string) error) *AdvisoryBuilderLinksCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *AdvisoryBuilderLinksCall) DoAndReturn(f func(context.Context, []string) error) *AdvisoryBuilderLinksCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RemoveArtifacts mocks base method.
func (m *AdvisoryBuilder) RemoveArtifacts(arg0 context.Context, arg1 func(driver.ArtifactHandle) bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveArtifacts", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveArtifacts indicates an expected call of RemoveArtifacts.
func (mr *AdvisoryBuilderMockRecorder) RemoveArtifacts(arg0, arg1 any) *AdvisoryBuilderRemoveArtifactsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveArtifacts", reflect.TypeOf((*AdvisoryBuilder)(nil).RemoveArtifacts), arg0, arg1)
	return &AdvisoryBuilderRemoveArtifactsCall{Call: call}
}

// AdvisoryBuilderRemoveArtifactsCall wrap *gomock.Call
type AdvisoryBuilderRemoveArtifactsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *AdvisoryBuilderRemoveArtifactsCall) Return(arg0 error) *AdvisoryBuilderRemoveArtifactsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *AdvisoryBuilderRemoveArtifactsCall) Do(f func(context.Context, func(driver.ArtifactHandle) bool) error) *AdvisoryBuilderRemoveArtifactsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *AdvisoryBuilderRemoveArtifactsCall) DoAndReturn(f func(context.Context, func(driver.ArtifactHandle) bool) error) *AdvisoryBuilderRemoveArtifactsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Self mocks base method.
func (m *AdvisoryBuilder) Self(arg0 context.Context, arg1 driver.Alias) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Self", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Self indicates an expected call of Self.
func (mr *AdvisoryBuilderMockRecorder) Self(arg0, arg1 any) *AdvisoryBuilderSelfCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Self", reflect.TypeOf((*AdvisoryBuilder)(nil).Self), arg0, arg1)
	return &AdvisoryBuilderSelfCall{Call: call}
}

// AdvisoryBuilderSelfCall wrap *gomock.Call
type AdvisoryBuilderSelfCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *AdvisoryBuilderSelfCall) Return(arg0 error) *AdvisoryBuilderSelfCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *AdvisoryBuilderSelfCall) Do(f func(context.Context, driver.Alias) error) *AdvisoryBuilderSelfCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *AdvisoryBuilderSelfCall) DoAndReturn(f func(context.Context, driver.Alias) error) *AdvisoryBuilderSelfCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Title mocks base method.
func (m *AdvisoryBuilder) Title(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Title", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Title indicates an expected call of Title.
func (mr *AdvisoryBuilderMockRecorder) Title(arg0, arg1 any) *AdvisoryBuilderTitleCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Title", reflect.TypeOf((*AdvisoryBuilder)(nil).Title), arg0, arg1)
	return &AdvisoryBuilderTitleCall{Call: call}
}

// AdvisoryBuilderTitleCall wrap *gomock.Call
type AdvisoryBuilderTitleCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *AdvisoryBuilderTitleCall) Return(arg0 error) *AdvisoryBuilderTitleCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *AdvisoryBuilderTitleCall) Do(f func(context.Context, string) error) *AdvisoryBuilderTitleCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *AdvisoryBuilderTitleCall) DoAndReturn(f func(context.Context, string) error) *AdvisoryBuilderTitleCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Updated mocks base method.
func (m *AdvisoryBuilder) Updated(arg0 context.Context, arg1 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Updated", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Updated indicates an expected call of Updated.
func (mr *AdvisoryBuilderMockRecorder) Updated(arg0, arg1 any) *AdvisoryBuilderUpdatedCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Updated", reflect.TypeOf((*AdvisoryBuilder)(nil).Updated), arg0, arg1)
	return &AdvisoryBuilderUpdatedCall{Call: call}
}

// AdvisoryBuilderUpdatedCall wrap *gomock.Call
type AdvisoryBuilderUpdatedCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *AdvisoryBuilderUpdatedCall) Return(arg0 error) *AdvisoryBuilderUpdatedCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *AdvisoryBuilderUpdatedCall) Do(f func(context.Context, time.Time) error) *AdvisoryBuilderUpdatedCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *AdvisoryBuilderUpdatedCall) DoAndReturn(f func(context.Context, time.Time) error) *AdvisoryBuilderUpdatedCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
