// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/quay/claircore/updater/driver (interfaces: ArtifactBuilder)
//
// Generated by this command:
//
//	mockgen -package=drivertest -typed=true -write_package_comment=false -destination=artifact_builder_mock.go -mock_names ArtifactBuilder=ArtifactBuilder github.com/quay/claircore/updater/driver ArtifactBuilder
//

package drivertest

import (
	context "context"
	iter "iter"
	reflect "reflect"
	time "time"

	packageurl_go "github.com/package-url/packageurl-go"
	cpe "github.com/quay/claircore/toolkit/types/cpe"
	cvss "github.com/quay/claircore/toolkit/types/cvss"
	driver "github.com/quay/claircore/updater/driver"
	gomock "go.uber.org/mock/gomock"
)

// ArtifactBuilder is a mock of ArtifactBuilder interface.
type ArtifactBuilder struct {
	ctrl     *gomock.Controller
	recorder *ArtifactBuilderMockRecorder
	isgomock struct{}
}

// ArtifactBuilderMockRecorder is the mock recorder for ArtifactBuilder.
type ArtifactBuilderMockRecorder struct {
	mock *ArtifactBuilder
}

// NewArtifactBuilder creates a new mock instance.
func NewArtifactBuilder(ctrl *gomock.Controller) *ArtifactBuilder {
	mock := &ArtifactBuilder{ctrl: ctrl}
	mock.recorder = &ArtifactBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *ArtifactBuilder) EXPECT() *ArtifactBuilderMockRecorder {
	return m.recorder
}

// Abandon mocks base method.
func (m *ArtifactBuilder) Abandon(ctx context.Context, reason error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Abandon", ctx, reason)
}

// Abandon indicates an expected call of Abandon.
func (mr *ArtifactBuilderMockRecorder) Abandon(ctx, reason any) *ArtifactBuilderAbandonCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Abandon", reflect.TypeOf((*ArtifactBuilder)(nil).Abandon), ctx, reason)
	return &ArtifactBuilderAbandonCall{Call: call}
}

// ArtifactBuilderAbandonCall wrap *gomock.Call
type ArtifactBuilderAbandonCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ArtifactBuilderAbandonCall) Return() *ArtifactBuilderAbandonCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ArtifactBuilderAbandonCall) Do(f func(context.Context, error)) *ArtifactBuilderAbandonCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ArtifactBuilderAbandonCall) DoAndReturn(f func(context.Context, error)) *ArtifactBuilderAbandonCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Attrs mocks base method.
func (m *ArtifactBuilder) Attrs(arg0 context.Context, arg1 iter.Seq2[string, string]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Attrs", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Attrs indicates an expected call of Attrs.
func (mr *ArtifactBuilderMockRecorder) Attrs(arg0, arg1 any) *ArtifactBuilderAttrsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Attrs", reflect.TypeOf((*ArtifactBuilder)(nil).Attrs), arg0, arg1)
	return &ArtifactBuilderAttrsCall{Call: call}
}

// ArtifactBuilderAttrsCall wrap *gomock.Call
type ArtifactBuilderAttrsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ArtifactBuilderAttrsCall) Return(arg0 error) *ArtifactBuilderAttrsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ArtifactBuilderAttrsCall) Do(f func(context.Context, iter.Seq2[string, string]) error) *ArtifactBuilderAttrsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ArtifactBuilderAttrsCall) DoAndReturn(f func(context.Context, iter.Seq2[string, string]) error) *ArtifactBuilderAttrsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Build mocks base method.
func (m *ArtifactBuilder) Build(arg0 context.Context) (driver.ArtifactHandle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Build", arg0)
	ret0, _ := ret[0].(driver.ArtifactHandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Build indicates an expected call of Build.
func (mr *ArtifactBuilderMockRecorder) Build(arg0 any) *ArtifactBuilderBuildCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Build", reflect.TypeOf((*ArtifactBuilder)(nil).Build), arg0)
	return &ArtifactBuilderBuildCall{Call: call}
}

// ArtifactBuilderBuildCall wrap *gomock.Call
type ArtifactBuilderBuildCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ArtifactBuilderBuildCall) Return(arg0 driver.ArtifactHandle, arg1 error) *ArtifactBuilderBuildCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ArtifactBuilderBuildCall) Do(f func(context.Context) (driver.ArtifactHandle, error)) *ArtifactBuilderBuildCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ArtifactBuilderBuildCall) DoAndReturn(f func(context.Context) (driver.ArtifactHandle, error)) *ArtifactBuilderBuildCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CPE mocks base method.
func (m *ArtifactBuilder) CPE(arg0 context.Context, arg1 *cpe.WFN) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CPE", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CPE indicates an expected call of CPE.
func (mr *ArtifactBuilderMockRecorder) CPE(arg0, arg1 any) *ArtifactBuilderCPECall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CPE", reflect.TypeOf((*ArtifactBuilder)(nil).CPE), arg0, arg1)
	return &ArtifactBuilderCPECall{Call: call}
}

// ArtifactBuilderCPECall wrap *gomock.Call
type ArtifactBuilderCPECall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ArtifactBuilderCPECall) Return(arg0 error) *ArtifactBuilderCPECall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ArtifactBuilderCPECall) Do(f func(context.Context, *cpe.WFN) error) *ArtifactBuilderCPECall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ArtifactBuilderCPECall) DoAndReturn(f func(context.Context, *cpe.WFN) error) *ArtifactBuilderCPECall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CVSSv3 mocks base method.
func (m *ArtifactBuilder) CVSSv3(arg0 context.Context, arg1 cvss.V3) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CVSSv3", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CVSSv3 indicates an expected call of CVSSv3.
func (mr *ArtifactBuilderMockRecorder) CVSSv3(arg0, arg1 any) *ArtifactBuilderCVSSv3Call {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CVSSv3", reflect.TypeOf((*ArtifactBuilder)(nil).CVSSv3), arg0, arg1)
	return &ArtifactBuilderCVSSv3Call{Call: call}
}

// ArtifactBuilderCVSSv3Call wrap *gomock.Call
type ArtifactBuilderCVSSv3Call struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ArtifactBuilderCVSSv3Call) Return(arg0 error) *ArtifactBuilderCVSSv3Call {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ArtifactBuilderCVSSv3Call) Do(f func(context.Context, cvss.V3) error) *ArtifactBuilderCVSSv3Call {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ArtifactBuilderCVSSv3Call) DoAndReturn(f func(context.Context, cvss.V3) error) *ArtifactBuilderCVSSv3Call {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CVSSv4 mocks base method.
func (m *ArtifactBuilder) CVSSv4(arg0 context.Context, arg1 cvss.V4) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CVSSv4", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CVSSv4 indicates an expected call of CVSSv4.
func (mr *ArtifactBuilderMockRecorder) CVSSv4(arg0, arg1 any) *ArtifactBuilderCVSSv4Call {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CVSSv4", reflect.TypeOf((*ArtifactBuilder)(nil).CVSSv4), arg0, arg1)
	return &ArtifactBuilderCVSSv4Call{Call: call}
}

// ArtifactBuilderCVSSv4Call wrap *gomock.Call
type ArtifactBuilderCVSSv4Call struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ArtifactBuilderCVSSv4Call) Return(arg0 error) *ArtifactBuilderCVSSv4Call {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ArtifactBuilderCVSSv4Call) Do(f func(context.Context, cvss.V4) error) *ArtifactBuilderCVSSv4Call {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ArtifactBuilderCVSSv4Call) DoAndReturn(f func(context.Context, cvss.V4) error) *ArtifactBuilderCVSSv4Call {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// EndOfLife mocks base method.
func (m *ArtifactBuilder) EndOfLife(arg0 context.Context, arg1 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EndOfLife", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// EndOfLife indicates an expected call of EndOfLife.
func (mr *ArtifactBuilderMockRecorder) EndOfLife(arg0, arg1 any) *ArtifactBuilderEndOfLifeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndOfLife", reflect.TypeOf((*ArtifactBuilder)(nil).EndOfLife), arg0, arg1)
	return &ArtifactBuilderEndOfLifeCall{Call: call}
}

// ArtifactBuilderEndOfLifeCall wrap *gomock.Call
type ArtifactBuilderEndOfLifeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ArtifactBuilderEndOfLifeCall) Return(arg0 error) *ArtifactBuilderEndOfLifeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ArtifactBuilderEndOfLifeCall) Do(f func(context.Context, time.Time) error) *ArtifactBuilderEndOfLifeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ArtifactBuilderEndOfLifeCall) DoAndReturn(f func(context.Context, time.Time) error) *ArtifactBuilderEndOfLifeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Purl mocks base method.
func (m *ArtifactBuilder) Purl(arg0 context.Context, arg1 *packageurl_go.PackageURL) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Purl", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Purl indicates an expected call of Purl.
func (mr *ArtifactBuilderMockRecorder) Purl(arg0, arg1 any) *ArtifactBuilderPurlCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Purl", reflect.TypeOf((*ArtifactBuilder)(nil).Purl), arg0, arg1)
	return &ArtifactBuilderPurlCall{Call: call}
}

// ArtifactBuilderPurlCall wrap *gomock.Call
type ArtifactBuilderPurlCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ArtifactBuilderPurlCall) Return(arg0 error) *ArtifactBuilderPurlCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ArtifactBuilderPurlCall) Do(f func(context.Context, *packageurl_go.PackageURL) error) *ArtifactBuilderPurlCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ArtifactBuilderPurlCall) DoAndReturn(f func(context.Context, *packageurl_go.PackageURL) error) *ArtifactBuilderPurlCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Severity mocks base method.
func (m *ArtifactBuilder) Severity(ctx context.Context, orig string, norm driver.Severity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Severity", ctx, orig, norm)
	ret0, _ := ret[0].(error)
	return ret0
}

// Severity indicates an expected call of Severity.
func (mr *ArtifactBuilderMockRecorder) Severity(ctx, orig, norm any) *ArtifactBuilderSeverityCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Severity", reflect.TypeOf((*ArtifactBuilder)(nil).Severity), ctx, orig, norm)
	return &ArtifactBuilderSeverityCall{Call: call}
}

// ArtifactBuilderSeverityCall wrap *gomock.Call
type ArtifactBuilderSeverityCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ArtifactBuilderSeverityCall) Return(arg0 error) *ArtifactBuilderSeverityCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ArtifactBuilderSeverityCall) Do(f func(context.Context, string, driver.Severity) error) *ArtifactBuilderSeverityCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ArtifactBuilderSeverityCall) DoAndReturn(f func(context.Context, string, driver.Severity) error) *ArtifactBuilderSeverityCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// State mocks base method.
func (m *ArtifactBuilder) State(arg0 context.Context, arg1 driver.ArtifactState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "State", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// State indicates an expected call of State.
func (mr *ArtifactBuilderMockRecorder) State(arg0, arg1 any) *ArtifactBuilderStateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "State", reflect.TypeOf((*ArtifactBuilder)(nil).State), arg0, arg1)
	return &ArtifactBuilderStateCall{Call: call}
}

// ArtifactBuilderStateCall wrap *gomock.Call
type ArtifactBuilderStateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ArtifactBuilderStateCall) Return(arg0 error) *ArtifactBuilderStateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ArtifactBuilderStateCall) Do(f func(context.Context, driver.ArtifactState) error) *ArtifactBuilderStateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ArtifactBuilderStateCall) DoAndReturn(f func(context.Context, driver.ArtifactState) error) *ArtifactBuilderStateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// VersionRange mocks base method.
func (m *ArtifactBuilder) VersionRange(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VersionRange", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// VersionRange indicates an expected call of VersionRange.
func (mr *ArtifactBuilderMockRecorder) VersionRange(arg0, arg1 any) *ArtifactBuilderVersionRangeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VersionRange", reflect.TypeOf((*ArtifactBuilder)(nil).VersionRange), arg0, arg1)
	return &ArtifactBuilderVersionRangeCall{Call: call}
}

// ArtifactBuilderVersionRangeCall wrap *gomock.Call
type ArtifactBuilderVersionRangeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ArtifactBuilderVersionRangeCall) Return(arg0 error) *ArtifactBuilderVersionRangeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ArtifactBuilderVersionRangeCall) Do(f func(context.Context, string) error) *ArtifactBuilderVersionRangeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ArtifactBuilderVersionRangeCall) DoAndReturn(f func(context.Context, string) error) *ArtifactBuilderVersionRangeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
