// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/quay/claircore/updater/driver (interfaces: UpdateBuilder)
//
// Generated by this command:
//
//	mockgen -package=drivertest -typed=true -write_package_comment=false -destination=update_builder_mock.go -mock_names UpdateBuilder=UpdateBuilder github.com/quay/claircore/updater/driver UpdateBuilder
//

package drivertest

import (
	context "context"
	reflect "reflect"

	driver "github.com/quay/claircore/updater/driver"
	gomock "go.uber.org/mock/gomock"
)

// UpdateBuilder is a mock of UpdateBuilder interface.
type UpdateBuilder struct {
	ctrl     *gomock.Controller
	recorder *UpdateBuilderMockRecorder
	isgomock struct{}
}

// UpdateBuilderMockRecorder is the mock recorder for UpdateBuilder.
type UpdateBuilderMockRecorder struct {
	mock *UpdateBuilder
}

// NewUpdateBuilder creates a new mock instance.
func NewUpdateBuilder(ctrl *gomock.Controller) *UpdateBuilder {
	mock := &UpdateBuilder{ctrl: ctrl}
	mock.recorder = &UpdateBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *UpdateBuilder) EXPECT() *UpdateBuilderMockRecorder {
	return m.recorder
}

// Abandon mocks base method.
func (m *UpdateBuilder) Abandon(ctx context.Context, reason error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Abandon", ctx, reason)
}

// Abandon indicates an expected call of Abandon.
func (mr *UpdateBuilderMockRecorder) Abandon(ctx, reason any) *UpdateBuilderAbandonCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Abandon", reflect.TypeOf((*UpdateBuilder)(nil).Abandon), ctx, reason)
	return &UpdateBuilderAbandonCall{Call: call}
}

// UpdateBuilderAbandonCall wrap *gomock.Call
type UpdateBuilderAbandonCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *UpdateBuilderAbandonCall) Return() *UpdateBuilderAbandonCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *UpdateBuilderAbandonCall) Do(f func(context.Context, error)) *UpdateBuilderAbandonCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *UpdateBuilderAbandonCall) DoAndReturn(f func(context.Context, error)) *UpdateBuilderAbandonCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Build mocks base method.
func (m *UpdateBuilder) Build(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Build", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Build indicates an expected call of Build.
func (mr *UpdateBuilderMockRecorder) Build(ctx any) *UpdateBuilderBuildCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Build", reflect.TypeOf((*UpdateBuilder)(nil).Build), ctx)
	return &UpdateBuilderBuildCall{Call: call}
}

// UpdateBuilderBuildCall wrap *gomock.Call
type UpdateBuilderBuildCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *UpdateBuilderBuildCall) Return(arg0 error) *UpdateBuilderBuildCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *UpdateBuilderBuildCall) Do(f func(context.Context) error) *UpdateBuilderBuildCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *UpdateBuilderBuildCall) DoAndReturn(f func(context.Context) error) *UpdateBuilderBuildCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ClearAdvisories mocks base method.
func (m *UpdateBuilder) ClearAdvisories(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearAdvisories", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearAdvisories indicates an expected call of ClearAdvisories.
func (mr *UpdateBuilderMockRecorder) ClearAdvisories(ctx any) *UpdateBuilderClearAdvisoriesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearAdvisories", reflect.TypeOf((*UpdateBuilder)(nil).ClearAdvisories), ctx)
	return &UpdateBuilderClearAdvisoriesCall{Call: call}
}

// UpdateBuilderClearAdvisoriesCall wrap *gomock.Call
type UpdateBuilderClearAdvisoriesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *UpdateBuilderClearAdvisoriesCall) Return(arg0 error) *UpdateBuilderClearAdvisoriesCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *UpdateBuilderClearAdvisoriesCall) Do(f func(context.Context) error) *UpdateBuilderClearAdvisoriesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *UpdateBuilderClearAdvisoriesCall) DoAndReturn(f func(context.Context) error) *UpdateBuilderClearAdvisoriesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateAdvisory mocks base method.
func (m *UpdateBuilder) CreateAdvisory(ctx context.Context, id string) (driver.AdvisoryBuilder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAdvisory", ctx, id)
	ret0, _ := ret[0].(driver.AdvisoryBuilder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAdvisory indicates an expected call of CreateAdvisory.
func (mr *UpdateBuilderMockRecorder) CreateAdvisory(ctx, id any) *UpdateBuilderCreateAdvisoryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAdvisory", reflect.TypeOf((*UpdateBuilder)(nil).CreateAdvisory), ctx, id)
	return &UpdateBuilderCreateAdvisoryCall{Call: call}
}

// UpdateBuilderCreateAdvisoryCall wrap *gomock.Call
type UpdateBuilderCreateAdvisoryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *UpdateBuilderCreateAdvisoryCall) Return(arg0 driver.AdvisoryBuilder, arg1 error) *UpdateBuilderCreateAdvisoryCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *UpdateBuilderCreateAdvisoryCall) Do(f func(context.Context, string) (driver.AdvisoryBuilder, error)) *UpdateBuilderCreateAdvisoryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *UpdateBuilderCreateAdvisoryCall) DoAndReturn(f func(context.Context, string) (driver.AdvisoryBuilder, error)) *UpdateBuilderCreateAdvisoryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateArtifact mocks base method.
func (m *UpdateBuilder) CreateArtifact(ctx context.Context) (driver.ArtifactBuilder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateArtifact", ctx)
	ret0, _ := ret[0].(driver.ArtifactBuilder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateArtifact indicates an expected call of CreateArtifact.
func (mr *UpdateBuilderMockRecorder) CreateArtifact(ctx any) *UpdateBuilderCreateArtifactCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateArtifact", reflect.TypeOf((*UpdateBuilder)(nil).CreateArtifact), ctx)
	return &UpdateBuilderCreateArtifactCall{Call: call}
}

// UpdateBuilderCreateArtifactCall wrap *gomock.Call
type UpdateBuilderCreateArtifactCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *UpdateBuilderCreateArtifactCall) Return(arg0 driver.ArtifactBuilder, arg1 error) *UpdateBuilderCreateArtifactCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *UpdateBuilderCreateArtifactCall) Do(f func(context.Context) (driver.ArtifactBuilder, error)) *UpdateBuilderCreateArtifactCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *UpdateBuilderCreateArtifactCall) DoAndReturn(f func(context.Context) (driver.ArtifactBuilder, error)) *UpdateBuilderCreateArtifactCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteAdvisory mocks base method.
func (m *UpdateBuilder) DeleteAdvisory(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAdvisory", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAdvisory indicates an expected call of DeleteAdvisory.
func (mr *UpdateBuilderMockRecorder) DeleteAdvisory(ctx, id any) *UpdateBuilderDeleteAdvisoryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAdvisory", reflect.TypeOf((*UpdateBuilder)(nil).DeleteAdvisory), ctx, id)
	return &UpdateBuilderDeleteAdvisoryCall{Call: call}
}

// UpdateBuilderDeleteAdvisoryCall wrap *gomock.Call
type UpdateBuilderDeleteAdvisoryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *UpdateBuilderDeleteAdvisoryCall) Return(arg0 error) *UpdateBuilderDeleteAdvisoryCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *UpdateBuilderDeleteAdvisoryCall) Do(f func(context.Context, string) error) *UpdateBuilderDeleteAdvisoryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *UpdateBuilderDeleteAdvisoryCall) DoAndReturn(f func(context.Context, string) error) *UpdateBuilderDeleteAdvisoryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetArtifact mocks base method.
func (m *UpdateBuilder) GetArtifact(ctx context.Context, h driver.ArtifactHandle) (*driver.ReadOnlyArtifact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArtifact", ctx, h)
	ret0, _ := ret[0].(*driver.ReadOnlyArtifact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArtifact indicates an expected call of GetArtifact.
func (mr *UpdateBuilderMockRecorder) GetArtifact(ctx, h any) *UpdateBuilderGetArtifactCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArtifact", reflect.TypeOf((*UpdateBuilder)(nil).GetArtifact), ctx, h)
	return &UpdateBuilderGetArtifactCall{Call: call}
}

// UpdateBuilderGetArtifactCall wrap *gomock.Call
type UpdateBuilderGetArtifactCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *UpdateBuilderGetArtifactCall) Return(arg0 *driver.ReadOnlyArtifact, arg1 error) *UpdateBuilderGetArtifactCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *UpdateBuilderGetArtifactCall) Do(f func(context.Context, driver.ArtifactHandle) (*driver.ReadOnlyArtifact, error)) *UpdateBuilderGetArtifactCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *UpdateBuilderGetArtifactCall) DoAndReturn(f func(context.Context, driver.ArtifactHandle) (*driver.ReadOnlyArtifact, error)) *UpdateBuilderGetArtifactCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PreviousOp mocks base method.
func (m *UpdateBuilder) PreviousOp(ctx context.Context) (*driver.UpdateMetadata, map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PreviousOp", ctx)
	ret0, _ := ret[0].(*driver.UpdateMetadata)
	ret1, _ := ret[1].(map[string]string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// PreviousOp indicates an expected call of PreviousOp.
func (mr *UpdateBuilderMockRecorder) PreviousOp(ctx any) *UpdateBuilderPreviousOpCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PreviousOp", reflect.TypeOf((*UpdateBuilder)(nil).PreviousOp), ctx)
	return &UpdateBuilderPreviousOpCall{Call: call}
}

// UpdateBuilderPreviousOpCall wrap *gomock.Call
type UpdateBuilderPreviousOpCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *UpdateBuilderPreviousOpCall) Return(arg0 *driver.UpdateMetadata, arg1 map[string]string, arg2 error) *UpdateBuilderPreviousOpCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *UpdateBuilderPreviousOpCall) Do(f func(context.Context) (*driver.UpdateMetadata, map[string]string, error)) *UpdateBuilderPreviousOpCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *UpdateBuilderPreviousOpCall) DoAndReturn(f func(context.Context) (*driver.UpdateMetadata, map[string]string, error)) *UpdateBuilderPreviousOpCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetOpAttr mocks base method.
func (m *UpdateBuilder) SetOpAttr(ctx context.Context, key, value string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetOpAttr", ctx, key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetOpAttr indicates an expected call of SetOpAttr.
func (mr *UpdateBuilderMockRecorder) SetOpAttr(ctx, key, value any) *UpdateBuilderSetOpAttrCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOpAttr", reflect.TypeOf((*UpdateBuilder)(nil).SetOpAttr), ctx, key, value)
	return &UpdateBuilderSetOpAttrCall{Call: call}
}

// UpdateBuilderSetOpAttrCall wrap *gomock.Call
type UpdateBuilderSetOpAttrCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *UpdateBuilderSetOpAttrCall) Return(arg0 error) *UpdateBuilderSetOpAttrCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *UpdateBuilderSetOpAttrCall) Do(f func(context.Context, string, string) error) *UpdateBuilderSetOpAttrCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *UpdateBuilderSetOpAttrCall) DoAndReturn(f func(context.Context, string, string) error) *UpdateBuilderSetOpAttrCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// StatAdvisory mocks base method.
func (m *UpdateBuilder) StatAdvisory(ctx context.Context, id string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StatAdvisory", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StatAdvisory indicates an expected call of StatAdvisory.
func (mr *UpdateBuilderMockRecorder) StatAdvisory(ctx, id any) *UpdateBuilderStatAdvisoryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StatAdvisory", reflect.TypeOf((*UpdateBuilder)(nil).StatAdvisory), ctx, id)
	return &UpdateBuilderStatAdvisoryCall{Call: call}
}

// UpdateBuilderStatAdvisoryCall wrap *gomock.Call
type UpdateBuilderStatAdvisoryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *UpdateBuilderStatAdvisoryCall) Return(arg0 bool, arg1 error) *UpdateBuilderStatAdvisoryCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *UpdateBuilderStatAdvisoryCall) Do(f func(context.Context, string) (bool, error)) *UpdateBuilderStatAdvisoryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *UpdateBuilderStatAdvisoryCall) DoAndReturn(f func(context.Context, string) (bool, error)) *UpdateBuilderStatAdvisoryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateAdvisory mocks base method.
func (m *UpdateBuilder) UpdateAdvisory(ctx context.Context, id string) (driver.AdvisoryBuilder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAdvisory", ctx, id)
	ret0, _ := ret[0].(driver.AdvisoryBuilder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAdvisory indicates an expected call of UpdateAdvisory.
func (mr *UpdateBuilderMockRecorder) UpdateAdvisory(ctx, id any) *UpdateBuilderUpdateAdvisoryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAdvisory", reflect.TypeOf((*UpdateBuilder)(nil).UpdateAdvisory), ctx, id)
	return &UpdateBuilderUpdateAdvisoryCall{Call: call}
}

// UpdateBuilderUpdateAdvisoryCall wrap *gomock.Call
type UpdateBuilderUpdateAdvisoryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *UpdateBuilderUpdateAdvisoryCall) Return(arg0 driver.AdvisoryBuilder, arg1 error) *UpdateBuilderUpdateAdvisoryCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *UpdateBuilderUpdateAdvisoryCall) Do(f func(context.Context, string) (driver.AdvisoryBuilder, error)) *UpdateBuilderUpdateAdvisoryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *UpdateBuilderUpdateAdvisoryCall) DoAndReturn(f func(context.Context, string) (driver.AdvisoryBuilder, error)) *UpdateBuilderUpdateAdvisoryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
