// Code generated by "stringer -linecomment -type ArtifactState"; DO NOT EDIT.

package driver

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ArtifactStateUnknown-0]
	_ = x[ArtifactStateVulnerable-1]
	_ = x[ArtifactStateUnaffected-2]
	_ = x[ArtifactStateEndOfLife-3]
}

const _ArtifactState_name = "unknownvulnerableunaffectedend-of-life"

var _ArtifactState_index = [...]uint8{0, 7, 17, 27, 38}

func (i ArtifactState) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ArtifactState_index)-1 {
		return "ArtifactState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ArtifactState_name[_ArtifactState_index[idx]:_ArtifactState_index[idx+1]]
}
