// Code generated by "stringer -linecomment -type Severity"; DO NOT EDIT.

package driver

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SeverityUnknown-0]
	_ = x[SeverityNegligible-1]
	_ = x[SeverityLow-2]
	_ = x[SeverityMedium-3]
	_ = x[SeverityHigh-4]
	_ = x[SeverityCritical-5]
}

const _Severity_name = "unknownnegligiblelowmediumhighcritical"

var _Severity_index = [...]uint8{0, 7, 17, 20, 26, 30, 38}

func (i Severity) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Severity_index)-1 {
		return "Severity(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Severity_name[_Severity_index[idx]:_Severity_index[idx+1]]
}
