// Embed is a helper to automatically write embed strings.
//
// This approach is taken instead of embedding an [io/fs.FS] implementation so
// that developers can get autocompletion on query names and avoid extra
// allocations on []byte to string conversions.
//
// With [unique] being available as of go1.23.0, the reverse-lookup overhead is
// also very small.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"io"
	"io/fs"
	"os"
	"path"
	"strconv"
	"strings"
	"text/template"
)

func main() {
	var code int
	defer func() {
		if code != 0 {
			os.Exit(code)
		}
	}()
	outfile := flag.String("o", `query_generated.go`, `output file ("-" to write to stdout)`)
	root := flag.String("root", `query`, `root directory of files to embed`)
	pat := flag.String("pat", `*.sql`, `file pattern`)
	flag.Parse()

	var out io.Writer
	if *outfile == "-" {
		out = os.Stdout
	} else {
		f, err := os.Create(*outfile)
		if err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(99)
		}
		defer f.Close()
		out = f
	}

	if err := Main(out, *root, *pat); err != nil {
		fmt.Fprintln(os.Stderr, err)
		code = 1
	}
}

// Main walks from "root" for files matching the glob "pat" and writes generated
// go code to "out".
func Main(out io.Writer, root, pat string) error {
	var data []Embed
	sys := os.DirFS(root)
	err := fs.WalkDir(sys, ".", func(p string, ent fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		n := ent.Name()
		if ok, _ := path.Match(pat, n); !ok {
			return nil
		}
		ext := path.Ext(n)
		name := strings.TrimSuffix(strings.ReplaceAll(p, "/", ""), ext)
		data = append(data, Embed{
			File:        path.Join(root, p),
			Name:        name,
			DisplayName: strconv.Quote(strings.TrimSuffix(n, ext)),
		})
		return nil
	})
	if err != nil {
		return err
	}

	t, err := template.New("Root").Parse(tmpl)
	if err != nil {
		return err
	}
	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return err
	}
	b, err := format.Source(buf.Bytes())
	if err != nil {
		return err
	}
	if _, err := io.Copy(out, bytes.NewReader(b)); err != nil {
		return err
	}
	return nil
}

// Embed describes a file to embed.
type Embed struct {
	File        string
	Name        string
	DisplayName string
}

const tmpl = `{{ define "var" }}
	//go:embed {{ .File }}
	{{ .Name }} string
{{- end -}}
{{ define "entry" }}
	unique.Make({{ .Name }}): {{ .DisplayName }},
{{- end -}}
// Autogenerated by internal/cmd/embed. DO NOT EDIT.

package postgres

import (
	_ "embed"
	"unique"
)

var (
{{- range . }}{{ template "var" . }}{{ end }}
)

// NameLookup maps interned SQL text back to a developer-meaningful name if the
// query is an embedded string.
var NameLookup = map[unique.Handle[string]]string {
{{- range . }}{{ template "entry" . }}{{ end }}
}
`
