// Code generated by "stringer -type Architecture -linecomment"; DO NOT EDIT.

package driver

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ArchAny-0]
	_ = x[Arch386-1]
	_ = x[ArchAMD64-2]
	_ = x[ArchArm-3]
	_ = x[ArchArm64-4]
	_ = x[ArchMips-5]
	_ = x[ArchMipsLE-6]
	_ = x[ArchMips64-7]
	_ = x[ArchMips64LE-8]
	_ = x[ArchPPC64-9]
	_ = x[ArchPPC64LE-10]
	_ = x[ArchRiscV64-11]
	_ = x[ArchS390X-12]
}

const _Architecture_name = "any386amd64armarm64mipsmipslemips64mips64leppc64ppc64leriscv64s390x"

var _Architecture_index = [...]uint8{0, 3, 6, 11, 14, 19, 23, 29, 35, 43, 48, 55, 62, 67}

func (i Architecture) String() string {
	if i < 0 || i >= Architecture(len(_Architecture_index)-1) {
		return "Architecture(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Architecture_name[_Architecture_index[i]:_Architecture_index[i+1]]
}
